// apps/angular-universal/src/app/counter/counter.component.ts
import {isPlatformBrowser} from "@angular/common";
import {Component, Inject, PLATFORM_ID, effect, signal} from "@angular/core";

@Component({
	selector: "app-counter",
	templateUrl: "./counter.component.html",
	styleUrls: ["./counter.component.css"],
})
export class CounterComponent {
	counter = signal(0);
	constructor(@Inject(PLATFORM_ID) private platformId: Object) {
		if (isPlatformBrowser(this.platformId)) {
			effect(() => {
				window.alert(this.counter());
			});
		}
	}
	incrementCounter() {
		this.counter.update((v) => v + 1);
	}
}

<div>
	<h1 class="counter">Licznik: {{ counter() }}</h1>
	<button (click)="incrementCounter()">Zwiększ</button>
</div>

// apps/next-js/src/counter/Counter.tsx
import {useState, useEffect} from "react";
import styles from "./Counter.module.css";
export default function Counter() {
	const [counter, setCounter] = useState(0);
	const incrementCounter = () => {
		setCounter((prevCounter) => prevCounter + 1);
	};
	useEffect(() => {
		alert(counter);
	});
	return (
		<div>
			<h1 className={styles.counter}>Licznik: {counter}</h1>
			<button onClick={incrementCounter}>Zwiększ</button>
		</div>
	);
}
