// apps/svelte-kit/src/counter/Counter.svelte
<script lang="ts">
	import {onMount} from "svelte";
	let counter = 0;
	const incrementCounter = () => {
		++counter;
	};
	let isMounted = false;
	onMount(() => {
		isMounted = true;
	});
	$: {
		if (isMounted) alert(counter);
	}
</script>

<div>
	<h1 class="counter">Licznik: {counter}</h1>
	<button on:click={incrementCounter}>Zwiększ</button>
</div>

<style>
	.counter {
		font-size: 30px;
	}
</style>

// apps/next-js/src/counter/Counter.tsx
import {useState, useEffect} from "react";
export default function Counter() {
	const [counter, setCounter] = useState(0);
	const incrementCounter = () => {
		setCounter((prevCounter) => prevCounter + 1);
	};
	useEffect(() => {
		alert(counter);
	});
	return (
		<div>
			<h1 className="counter">Licznik: {counter}</h1>
			<button onClick={incrementCounter}>Zwiększ</button>
		</div>
	);
}
