// apps/nuxt/counter/Counter.vue
<script setup lang="ts">
	import {watch, ref} from "vue";

	let counter = ref(0);
	watch(counter, (newCounter) => {
		alert(newCounter);
	});
	const incrementCounter = () => {
		++counter.value;
	};
</script>

<template>
	<div>
		<h1 class="counter">Licznik: {{ counter }}</h1>
		<button @click="incrementCounter">Zwiększ</button>
	</div>
</template>

<style scoped>
	.counter {
		font-size: 30px;
	}
</style>

// apps/svelte-kit/src/counter/Counter.svelte
<script lang="ts">
	import {onMount} from "svelte";
	let counter = 0;
	const incrementCounter = () => {
		++counter;
	};
	let isMounted = false;
	onMount(() => {
		isMounted = true;
	});
	$: {
		if (isMounted) alert(counter);
	}
</script>

<div>
	<h1 class="counter">Licznik: {counter}</h1>
	<button on:click={incrementCounter}>Zwiększ</button>
</div>

<style>
	.counter {
		font-size: 30px;
	}
</style>
